sudo: required
dist: trusty

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
before install:
  - chmod +x travis_ros_install.bash
  - chmod +x setup.bash
  - chmod +x travis_package_make.bash
